version: '3'
services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SECRET_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - "/srv/mariadb/data:/var/lib/mysql"
      - "/srv/mariadb/transfer:/transfer"

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SECRET_PASSWORD
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/srv/mongodb/data:/data/db"
      - "/srv/mongodb/transfer:/data/transfer"

  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: SECRET_PASSWORD
    volumes:
      - "/srv/postgres/data:/var/lib/postgresql/data"
      - "/srv/postgres/transfer:/transfer"

  mariadb_insecure:
    image: mariadb
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - "/srv/mariadb/data:/var/lib/mysql"
      - "/srv/mariadb/transfer:/transfer"

  mongodb-insecure:
    image: mongo
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/srv/mongodb-insecure/data:/data/db"
      - "/srv/mongodb-insecure/transfer:/data/transfer"

  postgresql-insecure:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "/srv/postgres-insecure/data:/var/lib/postgresql/data"
      - "/srv/postgres-insecure/transfer:/transfer"

